# Generated by Django 6.0.5 on 2026-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_date_joined_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('payment', 'Payment'), ('reports', 'Reports'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
